describe('Edit Transaction Admin Test Cases', () =>{
    it('Edit Transaction to Sending', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(4) > .px-sm-0').click()
        cy.get(':nth-child(4) > .submenu > :nth-child(1) > .nav-link').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/transaction_hdr')
        cy.get('[href="/transaction_edit_status/19"] > .fa').click()
        cy.get('.form-select').select('Sending')
        cy.get(':nth-child(3) > .btn').click()
        cy.get('.even > :nth-child(6)').contains('Sending').should('exist')
    })

    it('Edit Transaction to Arrived', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(4) > .px-sm-0').click()
        cy.get(':nth-child(4) > .submenu > :nth-child(1) > .nav-link').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/transaction_hdr')
        cy.get('[href="/transaction_edit_status/19"] > .fa').click()
        cy.get('.form-select').select('Arrived')
        cy.get(':nth-child(3) > .btn').click()
        cy.get('.even > :nth-child(6)').contains('Arrived').should('exist')
    })

    it('Edit Transaction to Failed', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(4) > .px-sm-0').click()
        cy.get(':nth-child(4) > .submenu > :nth-child(1) > .nav-link').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/transaction_hdr')
        cy.get('[href="/transaction_edit_status/20"] > .fa').click()
        cy.get('.form-select').select('Failed')
        cy.get(':nth-child(3) > .btn').click()
        cy.get(':nth-child(3) > :nth-child(6)').contains('Failed').should('exist')
    })
})