describe('Account Management', () => {
  it('Validating Login Page', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    //Validating objects needed for loging in
    cy.get('#email').should('exist')
    cy.get('#password').should('exist')
    cy.get('form > .row > .small > .text-light').should('exist')
    cy.get(':nth-child(2) > form > .btn').should('exist')
    cy.get(':nth-child(3) > .small > .text-light').should('exist')
  })

  it('Add Account', ()=>{
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('akimichi4455@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
    cy.get('.col-md-4 > .btn').click()
    cy.get('.form-group > :nth-child(1) > .form-control').type('User 13').wait(500)
    cy.get(':nth-child(2) > .form-control').type('user13@gmail.com') //email should not exist in database
    cy.get(':nth-child(3) > .form-control').type('123')
    cy.get(':nth-child(4) > .form-select').select('User')
    cy.get(':nth-child(5) > .form-control').type('User12345')
    cy.get('.modal-footer > .btn-primary').click()
    cy.contains('success').should('exist')
  })

  it('Add account but full name empty', ()=>{
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('akimichi4455@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
    cy.get('.col-md-4 > .btn').click()
    cy.get('.form-group > :nth-child(1) > .form-control').clear()
    cy.get(':nth-child(2) > .form-control').type('user12@gmail.com') //email should not exist in database
    cy.get(':nth-child(3) > .form-control').type('123')
    cy.get(':nth-child(4) > .form-select').select('User')
    cy.get(':nth-child(5) > .form-control').type('User12345')
    cy.get('.modal-footer > .btn-primary').click()
    cy.get('.modal-header').should('exist')
  })

  it('Add account but email empty', ()=>{
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('akimichi4455@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
    cy.get('.col-md-4 > .btn').click()
    cy.get('.form-group > :nth-child(1) > .form-control').type('User ini')
    cy.get(':nth-child(2) > .form-control').clear()
    cy.get(':nth-child(3) > .form-control').type('123')
    cy.get(':nth-child(4) > .form-select').select('User')
    cy.get(':nth-child(5) > .form-control').type('User12345')
    cy.get('.modal-footer > .btn-primary').click()
    cy.get('.modal-header').should('exist')
  })
})