describe('Address List (User) Test Case', () => {
  it('Add address valid', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('limfort01@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
    cy.get(':nth-child(4) > a > .btn').click()
    cy.get(':nth-child(4) > .text-start > a').click()
    cy.get('.text-center > .btn').click()
    cy.get(':nth-child(1) > .col-sm-8 > .form-control').type('User 01')
    cy.get(':nth-child(2) > .col-sm-8 > .form-control').type('Bumi 01')
    cy.get('.modal-content > form > .modal-footer > .btn-primary').click()
    cy.contains('success').should('exist')
  })

  it('Empty field', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('limfort01@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
    cy.get(':nth-child(4) > a > .btn').click()
    cy.get(':nth-child(4) > .text-start > a').click()
    cy.get('.text-center > .btn').click()
    cy.get(':nth-child(1) > .col-sm-8 > .form-control').clear()
    cy.get(':nth-child(2) > .col-sm-8 > .form-control').clear()
    cy.get('.modal-content > form > .modal-footer > .btn-primary').click()
    cy.get('#addAddress > .modal-dialog > .modal-content > .modal-header').should('exist')
  })

  it('Empty full name', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('limfort01@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
    cy.get(':nth-child(4) > a > .btn').click()
    cy.get(':nth-child(4) > .text-start > a').click()
    cy.get('.text-center > .btn').click()
    cy.get(':nth-child(1) > .col-sm-8 > .form-control').clear()
    cy.get(':nth-child(2) > .col-sm-8 > .form-control').type('Bumi')
    cy.get('.modal-content > form > .modal-footer > .btn-primary').click()
    cy.get('#addAddress > .modal-dialog > .modal-content > .modal-header').should('exist')
  })

  it('Empty address', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('limfort01@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
    cy.get(':nth-child(4) > a > .btn').click()
    cy.get(':nth-child(4) > .text-start > a').click()
    cy.get('.text-center > .btn').click()
    cy.get(':nth-child(1) > .col-sm-8 > .form-control').type('Ulala')
    cy.get(':nth-child(2) > .col-sm-8 > .form-control').clear()
    cy.get('.modal-content > form > .modal-footer > .btn-primary').click()
    cy.get('#addAddress > .modal-dialog > .modal-content > .modal-header').should('exist')
  })
})