describe('Edit Profile Form (User) Test Case', () => {
    it('Update fullname', () => {
      cy.viewport(1920, 1080)
      cy.visit('http://127.0.0.1:8000/login')
      cy.get('#email').type('limfort01@gmail.com')
      cy.get('#password').type('kokila123')
      cy.get(':nth-child(2) > form > .btn').click()
      cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
      cy.get(':nth-child(4) > a > .btn').click()
      cy.get(':nth-child(3) > .text-start > a').click()
      cy.get('.col > .input-group > .form-control').clear().type('Vanessa')
      cy.get('.form-group > .btn').click()
      cy.contains('success').should('exist')
    })

    it('Empty fullname', () => {
      cy.viewport(1920, 1080)
      cy.visit('http://127.0.0.1:8000/login')
      cy.get('#email').type('limfort01@gmail.com')
      cy.get('#password').type('kokila123')
      cy.get(':nth-child(2) > form > .btn').click()
      cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
      cy.get(':nth-child(4) > a > .btn').click()
      cy.get(':nth-child(3) > .text-start > a').click()
      cy.get('.col > .input-group > .form-control').clear()
      cy.get('.form-group > .btn').click()
      cy.url().should('be.equal', 'http://127.0.0.1:8000/editprofile_form')
    })
  })