describe('Password Change (User) Test Case', () => {
    it('Change password valid', () => {
    cy.viewport(1920, 1080)
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('limfort01@gmail.com')
    cy.get('#password').type('kokila123')
    cy.get(':nth-child(2) > form > .btn').click()
    cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
    cy.get(':nth-child(4) > a > .btn').click()
    cy.get(':nth-child(5) > .text-start > a').click()
    cy.get(':nth-child(2) > .col > .form-group > .input-group > .form-control').type('12345')
    cy.get(':nth-child(3) > .col > .form-group > .input-group > .form-control').type('12345')
    cy.get(':nth-child(4) > .btn').click().wait(2000)
    cy.contains('success').should('exist')
    })

    it('Confirmation new password invalid', () => {
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('limfort01@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/home')
        cy.get(':nth-child(4) > a > .btn').click()
        cy.get(':nth-child(5) > .text-start > a').click()
        cy.get(':nth-child(2) > .col > .form-group > .input-group > .form-control').type('12345')
        cy.get(':nth-child(3) > .col > .form-group > .input-group > .form-control').type('1234')
        cy.get(':nth-child(4) > .btn').click().wait(2000)
        cy.contains('The password confirmation does not match.').should('exist')
    })
})