describe('Category Test Cases for Admin', ()=>{
    it('Add category valid', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(5) > .nav-link').click()
        cy.get('.col-md-4 > .btn').click()
        cy.get('.input-group > .form-control').type('Kategori Baru')
        cy.get('.text-center > .btn').click()
        cy.contains('success').should('exist')
    })

    it('Add category but category name is empty', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(5) > .nav-link').click()
        cy.get('.col-md-4 > .btn').click()
        //cy.get('.input-group > .form-control').type('Kategori Baru')
        cy.get('.text-center > .btn').click()
        cy.get('.modal-header').should('exist')
    })

    it('Edit category valid', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(5) > .nav-link').click()
        cy.get('[href="category/edit/45451"] > .fa-regular').click()
        cy.get('.form-control').clear().type('Food2')
        cy.get('.form-group > .btn').click()
        cy.contains('success').should('exist')
    })

    it('Edit category but category name is empty', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(5) > .nav-link').click()
        cy.get('[href="category/edit/45451"] > .fa-regular').click()
        cy.get('.form-control').clear()
        cy.get('.form-group > .btn').click()
        cy.get('.form-control').should('exist')
    })
})