describe('Edit Item Test Cases for Admin', ()=>{
    it('Edit item valid', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(3) > .px-sm-0 > .ms-1').click()
        cy.get(':nth-child(3) > .submenu > :nth-child(1) > .nav-link').click()
        cy.get('[href="/master/header/edit/33331"] > .fa-regular').click()
        cy.get(':nth-child(4) > .form-control').clear().type('Nugget Biasa')
        cy.get(':nth-child(5) > .form-select').select('Clothes')
        cy.get(':nth-child(6) > .form-control').clear().type('12345678910')
        cy.get(':nth-child(7) > .form-control').clear().type('Deskripsi Baru')
        cy.get(':nth-child(8) > .form-control').clear().type('10')
        cy.get(':nth-child(9) > .form-control').clear().type('1000')
        cy.get(':nth-child(10) > .form-control').click().type('2024-11-12')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(3) > .btn').click()
        cy.contains('success').should('exist')
    })

    it('Edit item but item name is empty', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(3) > .px-sm-0 > .ms-1').click()
        cy.get(':nth-child(3) > .submenu > :nth-child(1) > .nav-link').click()
        cy.get('[href="/master/header/edit/33331"] > .fa-regular').click()
        cy.get(':nth-child(4) > .form-control').clear()
        cy.get(':nth-child(5) > .form-select').select('Clothes')
        cy.get(':nth-child(6) > .form-control').clear().type('12345678910')
        cy.get(':nth-child(7) > .form-control').clear().type('Deskripsi Baru')
        cy.get(':nth-child(8) > .form-control').clear().type('10')
        cy.get(':nth-child(9) > .form-control').clear().type('1000')
        cy.get(':nth-child(10) > .form-control').click().type('2024-11-12')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(3) > .btn').click()
        cy.get(':nth-child(3) > .btn').should('exist')
    })

    it('Edit item but stock is empty', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(3) > .px-sm-0 > .ms-1').click()
        cy.get(':nth-child(3) > .submenu > :nth-child(1) > .nav-link').click()
        cy.get('[href="/master/header/edit/33331"] > .fa-regular').click()
        cy.get(':nth-child(4) > .form-control').clear().type('Nama item baru')
        cy.get(':nth-child(5) > .form-select').select('Clothes')
        cy.get(':nth-child(6) > .form-control').clear().type('12345678910')
        cy.get(':nth-child(7) > .form-control').clear().type('Deskripsi Baru')
        cy.get(':nth-child(8) > .form-control').clear()
        cy.get(':nth-child(9) > .form-control').clear().type('1000')
        cy.get(':nth-child(10) > .form-control').click().type('2024-11-12')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(3) > .btn').click()
        cy.get(':nth-child(3) > .btn').should('exist')
    })

    it('Edit item but price is empty', () =>{
        cy.viewport(1920, 1080)
        cy.visit('http://127.0.0.1:8000/login')
        cy.get('#email').type('akimichi4455@gmail.com')
        cy.get('#password').type('kokila123')
        cy.get(':nth-child(2) > form > .btn').click()
        cy.url().should('be.equal', 'http://127.0.0.1:8000/admin')
        cy.get(':nth-child(3) > .px-sm-0 > .ms-1').click().type('Nama item baru')
        cy.get(':nth-child(3) > .submenu > :nth-child(1) > .nav-link').click()
        cy.get('[href="/master/header/edit/33331"] > .fa-regular').click()
        cy.get(':nth-child(4) > .form-control').clear()
        cy.get(':nth-child(5) > .form-select').select('Clothes')
        cy.get(':nth-child(6) > .form-control').clear().type('12345678910')
        cy.get(':nth-child(7) > .form-control').clear().type('Deskripsi Baru')
        cy.get(':nth-child(8) > .form-control').clear().type('10')
        cy.get(':nth-child(9) > .form-control').clear()
        cy.get(':nth-child(10) > .form-control').click().type('2024-11-12')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(11) > .form-select').select('Inactive')
        cy.get(':nth-child(3) > .btn').click()
        cy.get(':nth-child(3) > .btn').should('exist')
    })
})